apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: mb-napmap-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: mb-napmap-webapi-config
    literals:
      - database=mb-napmap
      - collection=stations

patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: mb-napmap-webapi
