/*
 * NAPMap Stations API
 *
 * NAPMap - Alternative fuel stations registry API
 *
 * API version: 1.0.0
 * Contact: maros.bednar@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package napmap

import (
	"github.com/gin-gonic/gin"
)

type StationsAPI interface {

	// GetStations Get /api/stations
	// Returns list of fuel stations with optional filtering
	GetStations(c *gin.Context)

	// CreateStation Post /api/stations
	// Register a new fuel station
	CreateStation(c *gin.Context)

	// GetStation Get /api/stations/:stationId
	// Returns details of a specific station
	GetStation(c *gin.Context)

	// UpdateStation Put /api/stations/:stationId
	// Update an existing station
	UpdateStation(c *gin.Context)

	// DeleteStation Delete /api/stations/:stationId
	// Soft delete - sets status to INACTIVE
	DeleteStation(c *gin.Context)
}
